### Get all haikus
GET sp3api.magnewei.com/api/haikus

### Create a new user
POST sp3api.magnewei.com/api/auth/register
Content-Type: application/json

{
  "username": "newuser",
  "password": "securepassword"
}

### Login request
POST sp3api.magnewei.com/api/auth/login
Content-Type: application/json

{
  "username": "newuser",
  "password": "securepassword"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

### Add admin role to the user
POST haiku.antonstengaard.dk/api/auth/user/addrole
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "role": "admin"
}

### Create a new haiku
POST sp3api.magnewei.com/api/haikus
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt_token}}


{
  "author": "Author10",
  "dateCreated": "2024-11-30",
  "haikuParts": [
    { "content": "Morning dew sparkles", "fiveSyllables": true },
    { "content": "On the blades of untouched grass", "fiveSyllables": false },
    { "content": "Nature wakes softly.", "fiveSyllables": true }
  ]
}