### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Populate the database with some data
GET {{url}}/haikus/populate/

### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/
Content-Type: application/json

{
  "username": "user",
  "password": "test123"
}

###
POST {{url}}/auth/login/
Content-Type: application/json

{
  "username": "user",
  "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

###
GET {{url}}/protected/user_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/protected/admin_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Add admin role to user
POST {{url}}/auth/user/addrole/
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "role": "admin"
}

### Get all haikus
GET {{url}}/haikus
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Get a specific haiku by ID
GET {{url}}/haikus/1
Accept: application/json
Authorization: Bearer {{jwt_token}}


### Create a new haiku
POST {{url}}/haikus
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "author": "Matsuo Basho",
  "dateCreated": "2023-10-01",
  "user": {

  },
  "haikuParts": [
    {
      "id": 1
    },
    {
      "id": 2
    },
    {
      "id": 3
    }
  ]
}

### Update an existing haiku
PUT {{url}}/haikus/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "author": "Updated Author",
  "dateCreated": "2023-10-02",
  "user": {
    "id": 1
  },
  "haikuParts": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ]
}

### Delete a haiku by ID
DELETE {{url}}/haikus/1
Authorization: Bearer {{jwt_token}}